### ISSUE TITLE
System components removal from Rebass

### ISSUE THREAD

**Issue by chrislombaard** [rebassjs/components#4]
@jxnblk  I'm currently building a component library at my company, after I was massively inspired by your work. Naturally I was using system-components with each of my components as a base, since it provided great utility functions. I noticed you moved system-components out to its own project repo, and removed the use of it from Rebass.

Would you still recommend the use of system-components to users building component libraries? Or was the use case for it in rebass just not worth it? Also, Could one use the 8 Rebass primitives as Bases in a component library, and then extend them with the functionality that system-components provide?

Anyways, love your work as always!

**Comment by jxnblk** [comment]
> Would you still recommend the use of system-components to users building component libraries?

Yes, just be sure to understand what it's doing under the hood and how the `is` and `extend` props work. With styled-components v4, I'd recommend using the built-in `as` prop instead

> Or was the use case for it in rebass just not worth it?

Yes, because Rebass can be used in a lot of different projects, the overhead of maintaining some of the functionality didn't seem worth it. See: rebassjs/rebass#474

> Also, Could one use the 8 Rebass primitives as Bases in a component library, and then extend them with the functionality that system-components provide?

Yes, exactly. If you're okay with this approach, I think it's a lot lighter weight and more React-like than using the system-components HOC

**Comment by chrislombaard** [comment]
> Yes, exactly. If you're okay with this approach, I think it's a lot lighter weight and more React-like than using the system-components HOC

@jxnblk So with that in mind, what are your plans for `system-components` then? Since I really like the convenience of it, it seems like something that people could really benefit from? But I do understand that it obfuscates much of its "magic" to the end-user. 

And thanks for the speedy reply 😄

**Comment by jxnblk** [comment]
This library will remain intact and I'll attempt to fix any bugs that might arise, but I'm not currently using `@rebass/components` in any project. The old package in the styled-system repo will probably be removed since I've moved this to a new org
